services:
    type: web
    name: medvoice-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MURF_API_KEY
        sync: false
      - key: FLASK_PORT
        value: "5001"
